### ISSUE TITLE
Any plan to finish the last two lecture notes?

### ISSUE THREAD

**Issue by jasonzhengz** [mwhittaker/consistency_in_distributed_systems#1]
Hi Michael I really like your lecture notes for those papers and very appreciate your contribution. Since the last two
* Chain Replication for Supporting High Throughput and Availability
* Coordination Avoidance in Database Systems

are still at "Coming soom" status, just wonder do you have any plan to finish them? That will be really helpful.

Thank you!

**Comment by mwhittaker** [comment]
Hi @elancer-zh! I'm absolutely delighted to hear that you enjoyed the notes :) The notes are definitely one of those things that I keep telling myself to finish but never manage to find the time to do it. I do think I'll finish them eventually, maybe this summer, but not anytime in the near future.

**Comment by jasonzhengz** [comment]
Thanks for the response!
